# Visual Exploration

#### You have a <a href = "https://docs.google.com/spreadsheets/d/1CYdbCfj0aF-bKNJ3lIPe6_rKkWT-IlCMXxNQtjkiD34/edit?usp=sharing">spreadsheet</a> that has the price of monthly cable bills, median income, and social security percentage increases. The data is from 1995 to 2022.

#### Create a line chart that hopefully reveals a trend between cable prices, median income and social security increases. Make the cable bill red; median income blue, and social security gray.

#### What would be your "thesis" based on your findings?

**Note about social security increases:**

Each year the U.S. government increases the amount of social security retired people receive. That increase is based on the annual inflation rate  and the political climate (or party in control). I have indexed the numbers so 1995 is 100, and each year after that the number reflects a percentage increase since 1995. So between 1995 at 100 and 1996 at 102.6 reflects a 2.6 percent increase. And between 1995 and 1997 reflects a 5.6 percent increase.

In [1]:
import pandas as pd

In [3]:
df_raw = pd.read_excel("cable-bill-only.xlsx")
df_raw

,Year,Avg. cable bill,Median household income,Social Security cost-of-living adjustment
0,1995,22.35,35249,100.0
1,1996,23.28,36689,102.6
2,1997,26.31,38229,105.6
3,1998,27.88,40148,107.8
4,1999,28.94,41994,109.2
5,2000,31.22,42349,111.9
6,2001,33.75,42710,115.8
7,2002,36.47,43057,118.9
8,2003,38.95,43564,120.5
9,2004,41.04,44684,123.0
10,2005,43.04,46242,126.4
11,2006,43.26,48451,131.6
12,2007,47.27,50740,135.9
13,2008,49.65,52029,139.0
14,2009,52.37,50221,147.1
15,2010,54.44,50046,147.1
16,2011,57.46,50502,147.1
17,2012,61.63,51371,152.4
18,2013,69.18,52250,155.0
19,2014,71.45,53657,157.3
20,2015,78.42,55775,159.0
21,2016,150.98,57617,159.0
22,2017,168.49,61372,159.3
23,2018,199.99,64324,161.3
24,2019,210.84,69560,164.1
25,2020,217.42,67521,165.7
26,2021,231.10,70784,167.0
27,2022,251.48,78075,172.9

# To-dos

### rename Social Security column (done)
### find pct_chges for cable bill
### find pct_chg for median household income
### find pct_cg for colA

In [10]:
## rename Social security column
df_raw.rename(columns = {'Social Security cost-of-living adjustment': 'SS-colA'}, \
          inplace = True) 
df_raw

    Year  Avg. cable bill  Median household income  SS-colA
0   1995            22.35                    35249    100.0
1   1996            23.28                    36689    102.6
2   1997            26.31                    38229    105.6
3   1998            27.88                    40148    107.8
4   1999            28.94                    41994    109.2
5   2000            31.22                    42349    111.9
6   2001            33.75                    42710    115.8
7   2002            36.47                    43057    118.9
8   2003            38.95                    43564    120.5
9   2004            41.04                    44684    123.0
10  2005            43.04                    46242    126.4
11  2006            43.26                    48451    131.6
12  2007            47.27                    50740    135.9
13  2008            49.65                    52029    139.0
14  2009            52.37                    50221    147.1
15  2010            54.44                    50046    147.1
16  2011            57.46                    50502    147.1
17  2012            61.63                    51371    152.4
18  2013            69.18                    52250    155.0
19  2014            71.45                    53657    157.3
20  2015            78.42                    55775    159.0
21  2016           150.98                    57617    159.0
22  2017           168.49                    61372    159.3
23  2018           199.99                    64324    161.3
24  2019           210.84                    69560    164.1
25  2020           217.42                    67521    165.7
26  2021           231.10                    70784    167.0
27  2022           251.48                    78075    172.9

In [11]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     28 non-null     int64
 1   Avg. cable bill          28 non-null     float64
 2   Median household income  28 non-null     int64
 3   SS-colA                  28 non-null     float64
dtypes: float64(2), int64(2)
memory usage: 1.0 KB